services:
  caddy:
    image: custom-caddy:latest
    container_name: caddy
    restart: unless-stopped
    command: ["caddy", "run", "--watch"]
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ${DOCKER_DIRECTORY}/caddy/conf:/etc/caddy
      - ${DOCKER_DIRECTORY}/caddy/site:/srv
      - ${DOCKER_DIRECTORY}/caddy/data:/data
      - ${DOCKER_DIRECTORY}/caddy/config:/config
