services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${DOCKER_DIRECTORY}/caddy/conf:/etc/caddy
      - ${DOCKER_DIRECTORY}/caddy/site:/srv
      - ${DOCKER_DIRECTORY}/caddy/data:/data
      - ${DOCKER_DIRECTORY}/caddy/config:/config
