services:
  chartdb:
      image: ghcr.io/chartdb/chartdb:latest
      container_name: chartdb
      restart: unless-stopped
      environment:
        - OPENAI_API_KEY=""
      expose:
        - 80
      networks:
        - home-net
        
networks:
  home-net:
    external: true
