services:
  cloudbeaver:
      image: dbeaver/cloudbeaver:latest
      container_name: cloudbeaver
      restart: unless-stopped
      ports:
          - 8088:8978
      volumes:
          - ${DOCKER_DIRECTORY}/cloudbeaver/:/opt/cloudbeaver/workbench
