services:
  core-keeper:
    container_name: core-keeper-dedicated
    image: escaping/core-keeper-dedicated
    restart: unless-stopped
    ports:
      - "27015:27015/udp"
    volumes:
      - /media/SSD-D1/docker-data/core-keeper/ckfile:/home/steam/core-keeper-dedicated
      - /media/SSD-D1/docker-data/core-keeper/data:/home/steam/core-keeper-data
    stop_grace_period: 2m
