services:
  docuseal:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    volumes:
      - ${DOCKER_DIRECTORY}/docuseal:/data/docuseal
    environment:
      - FORCE_SSL=${HOST}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
    networks:
      - docuseal-net
      - home-net

  postgres:
    image: postgres:18
    volumes:
      - ${DOCKER_DIRECTORY}/docuseal/postgres:/var/lib/postgresql/18/docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d docuseal"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - docuseal-net

networks:
  docuseal-net:
    driver: bridge
    internal: true

  home-net:
    external: true
