services:
  dozzle-agent:
    image: amir20/dozzle:latest
    restart: unless-stopped
    container_name: dozzle-agent
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    expose:
      - "7007"
    networks:
      home-net:
        aliases:
          - dozzle-${DOCKER_NODE}
          
networks:
  home-net:
    external: true
