services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_REMOTE_AGENT=${REMOTE_AGENT}
    expose:
      - "8080"
    networks:
      - home-net

networks:
  home-net:
    external: true
