services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_MODE=swarm
    deploy:
      mode: global
    ports:
      - 8080:8080
    expose:
      - "8080"
    networks:
      - home-net
      - dozzle

networks:
  home-net:
    external: true
  dozzle:
    driver: overlay
