services:
    filebrowser:
        image: filebrowser/filebrowser:s6
        container_name: filebrowser
        restart: unless-stopped
        privileged: true
        volumes:
            - ${ROOT_DIRECTORY}:/srv
            - ${DOCKER_DIRECTORY}/filebrowser/filebrowser.db:/database/filebrowser.db
            - ${DOCKER_DIRECTORY}/filebrowser/settings.json:/config/settings.json
        environment:
            - PUID=0
            - PGID=0
        ports:
            - 8010:80
