services:
    filebrowser:
        image: filebrowser/filebrowser:s6
        container_name: filebrowser
        restart: unless-stopped
        privileged: true
        volumes:
            - ${ROOT_DIRECTORY}:/srv
            - ${DOCKER_DIRECTORY}/filebrowser/database:/database
            - ${DOCKER_DIRECTORY}/filebrowser/config:/config
        environment:
            - PUID=0
            - PGID=0
        ports:
            - 8010:8080
