services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${TIMEZONE}
    volumes:
      - ${DOCKER_DIRECTORY}/n8n/data:/home/node/.n8n
      - ${DOCKER_DIRECTORY}/n8n/files:/files
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docker-titan.rule=Host(`n8n.docker-titan.local`)"
      - "traefik.http.routers.docker-titan.entrypoints=web"
      - "traefik.http.services.docker-titan.loadbalancer.server.port=5678"
    networks:
      - local
      
networks:
  local:
    external: true
