services:
  netbird:
    image: netbirdio/netbird:latest
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - NB_SETUP_KEY=${SETUP_KEY}
      - NB_MANAGEMENT_URL=${MANAGEMENT_URL}
    volumes:
      - ${DOCKER_DIRECTORY}/netbird:/var/lib/netbird
