services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest # or ghcr.io/zoeyvid/npmplus:latest
    restart: always
    ports:
      - "81:81"
      - "1000-65535:1000-65535"
    volumes:
      - "${DOCKER_DIRECTORY}/npmplus:/data"
    environment:
      - "TZ=Asia/Jakarta"
      - "ACME_EMAIL=${EMAIL}"
