services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest # or ghcr.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "${DOCKER_DIRECTORY}/npmplus:/data"
    environment:
      - "TZ=Asia/Jakarta"
      - "ACME_EMAIL=${EMAIL}"
