services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest # or ghcr.io/zoeyvid/npmplus:latest
    restart: always
    network_mode: host
    volumes:
      - "${DOCKER_DIRECTORY}/npmplus:/data"
    environment:
      - "TZ=Asia/Jakarta"
      - "ACME_EMAIL=${EMAIL}"
      - "NGINX_PORT_80=8980"    # Change HTTP to port 8080
      - "NGINX_PORT_443=8943"   # Change HTTPS to port 8443
