version: "3.3"
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: always
    volumes:
      - ${DOCKER_DIRECTORY}/open-webui:/app/backend/data
    expose:
      - "8080"
    networks:
      - home-net

networks:
  home-net:
    external: true
  dockge_default:
    external: true
  ollama_default:
    external: true
  searxng_searxng:
    external: true
  tika_default:
    external: true
