services:
  openclaw-gateway:
    image: alpine/openclaw:latest
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      # CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      # CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      # CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${DOCKER_DIRECTORY}/openclaw/config:/home/node/.openclaw
      - ${DOCKER_DIRECTORY}/openclaw/workspace:/home/node/.openclaw/workspace
    networks:
      - home-net
    expose:
      - 18789
      - 18790
      - 18793
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "${OPENCLAW_GATEWAY_BIND:-lan}",
        "--port",
        "18789",
      ]

  openclaw-cli:
    image: alpine/openclaw:latest
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      BROWSER: echo
      # CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      # CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      # CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${DOCKER_DIRECTORY}/openclaw/config:/home/node/.openclaw
      - ${DOCKER_DIRECTORY}/openclaw/workspace:/home/node/.openclaw/workspace
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["sh", "-lc", "tail -f /dev/null"]

networks:
  home-net:
    external: true
