services:
  # caddy:
  #   image: custom-caddy:latest
  #   container_name: caddy
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "443:443/udp"
  #   volumes:
  #     - ${DOCKER_DIRECTORY}/caddy/conf:/etc/caddy
  #     - ${DOCKER_DIRECTORY}/caddy/site:/srv
  #     - ${DOCKER_DIRECTORY}/caddy/data:/data
  #     - ${DOCKER_DIRECTORY}/caddy/config:/config
  #   network:
  #     - proxy_network

  rathole:
    image: rapiz1/rathole
    container_name: rathole
    restart: unless-stopped
    network_mode: host
    volumes:
        - ${DOCKER_DIRECTORY}/rathole:/etc/rathole
    command: /etc/rathole/config.toml
#     network:
#       - proxy_network

# network:
#   proxy_network:
#     external: true
