services:
  rathole:
    image: rapiz1/rathole
    container_name: rathole
    restart: unless-stopped    
    volumes:
        - ${DOCKER_DIRECTORY}/rathole:/etc/rathole
    command: /etc/rathole/config.toml
