services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  # Required, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ${DOCKER_DIRECTORY}/seafile/seafile-mysql:/var/lib/mysql  # Required, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:11.0-latest
    container_name: seafile
    restart: unless-stopped
    ports:
#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - ${DOCKER_DIRECTORY}/seafile/seafile-storage:/shared   # Required, specifies the path to Seafile data persistent store.
      - ${STORAGE_DIRECTORY}/seafile/seafile-data:/shared/seafile/seafile-data
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${DB_PASSWORD}  # Required, the value should be root's password of MySQL service.
      - TIME_ZONE=Asia/Jakarta  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=${ADMIN_EMAIL} # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=${ADMIN_PASSWORD}     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=${SERVER_HOSTNAME} # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    expose:
      - "80"
    networks:
      - seafile-net
      - home-net

networks:
  seafile-net:
  home-net:
