services:
  speedtest-tracker:
    image: henrywhitaker3/speedtest-tracker
    container_name: speedtest-tracker
    restart: unless-stopped
    volumes:
      - ${DOCKER_DIRECTORY}/speedtest:/config
    environment:
      - TZ=Asia/Jakarta
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    expose:
      - "80"
    networks:
      - home-net
      
networks:
  home-net:
    external: true
