# Container Reverse Proxy
services:
  traefik:
    image: traefik:latest
    container_name: traefik-crp
    command:
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
