services:
  connector-1:
    image: twingate/connector:1
    container_name: twingate-1
    restart: unless-stopped
    privileged: true
    environment:
        #- TWINGATE_NETWORK=
        #- TWINGATE_ACCESS_TOKEN=
        #- TWINGATE_REFRESH_TOKEN=
        - TWINGATE_LABEL_HOSTNAME=`hostname`
        - TWINGATE_LABEL_DEPLOYED_BY=docker
  connector-2:
    image: twingate/connector:1
    container_name: twingate-2
    restart: unless-stopped
    privileged: true
    environment:
        #- TWINGATE_NETWORK=
        #- TWINGATE_ACCESS_TOKEN=
        #- TWINGATE_REFRESH_TOKEN=
        - TWINGATE_LABEL_HOSTNAME=`hostname`
        - TWINGATE_LABEL_DEPLOYED_BY=docker
