services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
        - ${DOCKER_DIRECTORY}/uptime-kuma:/app/data
    expose:
      - "3001"
    networks:
      - home-net

networks:
  home-net:
    external: true
